import { AutographPlayer, CardPlayer } from "./util.js";

export const autographPlayers = [
	new AutographPlayer('Adam Jones', 'BAL', 'CF', 1000, 1),
	new AutographPlayer('Akinori Iwamura',	'YS (Japan)', 'IF', 1000, 1),
	new AutographPlayer('Alex Gordon',	'KC', 'OF', 1000, 1),
	new AutographPlayer('Alex Rodriguez', 'NYY', '3B', 25000, 1),
	new AutographPlayer('Andy Pettitte', 'NYY', 'P', 1000, 1),
	new AutographPlayer('Aubrey Huff',	'BAL', 'IF', 1000, 1),
	new AutographPlayer('Billy Ripken',	'BAL', 'IF', 1000, 1),
	new AutographPlayer('Boof Bonsor',	'MIN', 'P', 1000, 1),
	new AutographPlayer('Brian Bannister',	'KC', 'P', 1000, 1),
	new AutographPlayer('Brian Bruney',	'NYY', 'P', 1000, 1),
	new AutographPlayer('Brian Burres',	'BAL', 'P', 1000, 1),
	new AutographPlayer('Brian Matusz',	'BAL', 'P', 1000, 1),
	new AutographPlayer('Brian Roberts',	'BAL', 'IF', 1000, 1),
	new AutographPlayer('David Ortiz', 'BOS', 'DH', 1000, 1),
	new AutographPlayer('Denard Span', 'MIN', 'OF', 1000, 1),
	new AutographPlayer('Dennis Sarfate', 'SH (Japan)', 'P', 1000, 1),
	new AutographPlayer('Derek Jeter', 'NYY', 'SS', 1000, 1),
	new AutographPlayer('Dick Hall',	'BAL', 'P', 1000, 1),
	new AutographPlayer('Edwar Ramirez',	'NYY', 'P', 1000, 1),
	new AutographPlayer('Edwin Jackson',	'TB', 'P', 1000, 1),
	new AutographPlayer('Erik Bedard',	'BAL', 'P', 1000, 1),
	new AutographPlayer('Garrett Olson', 'BAL', 'P', 1000, 1),
	new AutographPlayer('George Sherrill',	'BAL', 'P', 1000, 1),
	new AutographPlayer('Hank Aaron', 'ATL', 'OF', 1000, 1),
	new AutographPlayer('James Shields',	'TB', 'P', 1000, 1),
	new AutographPlayer('Jamie Walker',	'BAL', 'P', 1000, 1),
	new AutographPlayer('Jered Weaver',	'LAA', 'P', 1000, 1),
	new AutographPlayer('Jim Hickey',	'TB', 'Coach', 1000, 1),
	new AutographPlayer('Jim Palmer', 'BAL', 'P', 1000, 1),
	new AutographPlayer('Joe Maddon',	'TB', 'Manager', 1000, 1),
	new AutographPlayer('Jorge Posada', 'NYY', 'C', 1000, 1),
	new AutographPlayer('Justin Masterson', 'BOS', 'P', 1000), 1, 
	new AutographPlayer('Kevin Millar', 'BAL', 'IF', 1000, 1),
	new AutographPlayer('Kevin Slowey',	'MIN', 'P', 1000, 1),
	new AutographPlayer('Larry Sheets',	'BAL', 'OF', 1000, 1),
	new AutographPlayer('Luke Scott',	'BAL', 'OF', 1000, 1),
	new AutographPlayer('Mark Grudzielanek',	'KC', 'IF', 1000, 1),
	new AutographPlayer('Mark Teahen',	'KC', 'OF', 1000, 1),
	new AutographPlayer('Matt Garza', 'TB', 'P', 1000, 1),
	new AutographPlayer('Melvin Mora',	'BAL', 'IF', 1000, 1),
	new AutographPlayer('Nelson Figueroa',	'NYM', 'P', 1000, 1),
	new AutographPlayer('Nick Swisher', 'NYY', 'OF', 1000, 1),
	new AutographPlayer('Paul Blair',	'BAL', 'OF', 1000, 1),
	new AutographPlayer('Rick Dempsey',	'BAL', 'C', 1000, 1),
	new AutographPlayer('Scott Kazmir',	'TB', 'P', 1000, 1),
	new AutographPlayer('Sean Casey',	'BOS', 'IF', 1000, 1),
	new AutographPlayer('Terry Francona', 'BOS', 'Manager', 1000, 1),
	new AutographPlayer('Tim Kurkjian', 'ESPN', 'Reporter', 1000, 1),
	new AutographPlayer('Tim Teufel', 'NYM', 'IF', 1000, 1),
	new AutographPlayer('Torii Hunter', 'LAA', 'OF', 1000, 1),
	new AutographPlayer('Yogi Berra', 'NYY', 'C', 1000, 1),
];

export const cardsPlayers = [
	new CardPlayer('Michael Strahan', 'Fleer', '2000', 100, 1),
	new CardPlayer('Peyton Manning', 'Topps Chrome', '2003', 250, 1),
	new CardPlayer('Troy Polamalu', 'Topps', '2005', 100, 1),
];